### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by roll** [conda-forge/tableschema-feedstock#16]
To resolve https://github.com/frictionlessdata/implementations/issues/34

```
    - six >=1.9
    - click >=3.3
    - requests >=2.5
    - python-dateutil >=2.4
    - jsonschema >=2.5
    - unicodecsv >=0.14
    - isodate >=0.5.4
    - rfc3986 >=1.1.0
    - tabulator >=1.20
```

**Comment by ocefpaf** [comment]
Do you want to send a PR to fix that? All you want to do is to update the deps and bump the build number. Also, consider adding yourself as a maintainer so you can fix and merge this next time :wink:
